lib/green_light.ex
lib/link/authorization.ex
lib/link/studies.ex
lib/link/studies/study.ex
lib/link/users/profile.ex
lib/link_web/templates/study/index.html.eex
lib/link_web/templates/user_profile/form.html.eex
priv/repo/migrations/20201213180227_add_researcher_flag_to_users_table.exs
priv/repo/migrations/20201213191000_drop_researcher_from_studies.exs
test/green_light/green_light/ecto/query_test.exs
test/green_light/green_light/permission_map_test.exs
test/green_light/green_light_test.exs
test/link/authorization_test.exs
test/link_web/controllers/participant_controller_test.exs
test/link_web/controllers/study_controller_test.exs
test/support/factories.ex

Creating studies is now restricted to researchers.

Added researcher flag to user profile

---

core/lib/core_web/ui/progress_bar.ex
core/mix.exs
core/priv/gettext/en/LC_MESSAGES/eyra-assignment.po
core/priv/gettext/en/LC_MESSAGES/eyra-crew.po
core/priv/gettext/en/LC_MESSAGES/eyra-marketplace.po
core/priv/gettext/en/LC_MESSAGES/eyra-submission.po
core/priv/gettext/en/LC_MESSAGES/eyra-ui.po
core/priv/gettext/en/LC_MESSAGES/link-assignment.po
core/priv/gettext/en/LC_MESSAGES/link-survey.po
core/priv/gettext/eyra-assignment.pot
core/priv/gettext/eyra-crew.pot
core/priv/gettext/eyra-submission.pot
core/priv/gettext/eyra-ui.pot
core/priv/gettext/link-assignment.pot
core/priv/gettext/link-survey.pot
core/priv/gettext/nl/LC_MESSAGES/eyra-assignment.po
core/priv/gettext/nl/LC_MESSAGES/eyra-crew.po
core/priv/gettext/nl/LC_MESSAGES/eyra-marketplace.po
core/priv/gettext/nl/LC_MESSAGES/eyra-submission.po
core/priv/gettext/nl/LC_MESSAGES/eyra-ui.po
core/priv/gettext/nl/LC_MESSAGES/link-assignment.po
core/priv/gettext/nl/LC_MESSAGES/link-survey.po
core/systems/assignment/context.ex
core/systems/assignment/landing_page.ex
core/systems/assignment/model.ex
core/systems/campaign/model.ex
core/systems/crew/context.ex
core/systems/crew/task_model.ex
core/test/systems/campaign/monitor_view_test.exs
core/test/systems/crew/context_test.exs

… when task is started b…ut not completed

Added cancel feature to Assignment.LandingPage

---

core/priv/repo/migrations/20211208210633_fix_web_push_subscriptions.exs

... so it can contain longer values

Change type of endpoint in web_push_subscriptions to text 

---

core/systems/scholar/context.ex

Fixed bug in handle_features_updated where old_class_codes == nil

---

core/assets/package-lock.json

Revert "Bump browserslist from 4.14.5 to 4.21.4 in /core/assets"

---

core/assets/package-lock.json

Revert "Bump is-svg and postcss-svgo in /core/assets"

---

core/bundles/next/lib/home/landing_page_html/show.html.eex
core/priv/gettext/nl/LC_MESSAGES/eyra-assignment.po

- changed project to program on Eyra.co website
- changed text liss in next based on feedback Joris (centerdata)

Adjust copy

---

core/assets/js/pdf_viewer.js

Closes #624 
Tested it, it works. See whether you like it.

links clickable in pdfs from pdf.js

---

core/priv/gettext/en/LC_MESSAGES/eyra-assignment.po
core/priv/gettext/en/LC_MESSAGES/eyra-crew.po
core/priv/gettext/nl/LC_MESSAGES/eyra-assignment.po
core/priv/gettext/nl/LC_MESSAGES/eyra-crew.po

Project monitor copy

---

core/priv/gettext/en/LC_MESSAGES/eyra-assignment.po
core/priv/gettext/nl/LC_MESSAGES/eyra-assignment.po

Project port privacy copy

---

core/priv/gettext/en/LC_MESSAGES/eyra-account.po
core/priv/gettext/en/LC_MESSAGES/eyra-user.po
core/priv/gettext/nl/LC_MESSAGES/eyra-account.po
core/systems/email/email/account_confirmation_instructions.html.eex
core/systems/email/email/account_confirmation_instructions.text.eex
core/systems/email/email/reset_password_instructions.html.eex
core/systems/email/email/reset_password_instructions.text.eex
core/test/core_web/live/user/confirm_token_test.exs

- Changed activation copy
- Changed forgot password / request new password copy (based on feedback Florian)

Outlook safelink copy

---

core/priv/gettext/en/LC_MESSAGES/eyra-assignment.po
core/priv/gettext/en/LC_MESSAGES/eyra-workflow.po

644 add submission benchmark task copy

---

core/priv/gettext/en/LC_MESSAGES/errors.po
core/priv/gettext/en/LC_MESSAGES/eyra-assignment.po
core/priv/gettext/en/LC_MESSAGES/eyra-enums.po
core/priv/gettext/en/LC_MESSAGES/eyra-graphite.po
core/priv/gettext/en/LC_MESSAGES/eyra-instruction.po
core/priv/gettext/nl/LC_MESSAGES/eyra-graphite.po
core/priv/gettext/nl/LC_MESSAGES/eyra-instruction.po

Rank prefer emiel copy

---

core/priv/gettext/en/LC_MESSAGES/eyra-graphite.po
core/priv/gettext/nl/LC_MESSAGES/eyra-graphite.po

Submission task copy adjustments

Rank prefer copy

---

core/priv/gettext/en/LC_MESSAGES/eyra-enums.po
core/priv/gettext/en/LC_MESSAGES/eyra-graphite.po
core/priv/gettext/en/LC_MESSAGES/eyra-project.po
core/priv/gettext/eyra-enums.pot
core/priv/gettext/eyra-graphite.pot
core/priv/gettext/eyra-project.pot
core/priv/gettext/nl/LC_MESSAGES/eyra-enums.po
core/priv/gettext/nl/LC_MESSAGES/eyra-graphite.po
core/priv/gettext/nl/LC_MESSAGES/eyra-project.po
core/systems/graphite/_public.ex
core/systems/graphite/leaderboard_content_builder.ex
core/systems/graphite/leaderboard_content_page.ex
core/systems/graphite/leaderboard_model.ex
core/systems/graphite/leaderboard_settings_form.ex
core/systems/graphite/leaderboard_upload_form.ex
core/systems/project/item_model.ex

Updates for leaderboard based on Adrienne's feedback.

Update leaderboard card description

---

core/priv/gettext/en/LC_MESSAGES/eyra-account.po
core/priv/gettext/en/LC_MESSAGES/eyra-advert.po
core/priv/gettext/en/LC_MESSAGES/eyra-assignment.po
core/priv/gettext/en/LC_MESSAGES/eyra-enums.po
core/priv/gettext/en/LC_MESSAGES/eyra-home.po
core/priv/gettext/en/LC_MESSAGES/eyra-next.po
core/priv/gettext/en/LC_MESSAGES/eyra-ui.po
core/priv/gettext/nl/LC_MESSAGES/eyra-account.po
core/priv/gettext/nl/LC_MESSAGES/eyra-home.po
core/priv/gettext/nl/LC_MESSAGES/eyra-next.po
core/priv/gettext/nl/LC_MESSAGES/eyra-ui.po
core/test/core_web/controllers/user_session_controller_test.exs

Panl specific copy changes and my profile --> account.

Master copy link software

---

core/priv/gettext/de/LC_MESSAGES/eyra-assignment.po
core/priv/gettext/de/LC_MESSAGES/eyra-consent.po
core/priv/gettext/de/LC_MESSAGES/eyra-ui.po
core/priv/gettext/en/LC_MESSAGES/eyra-assignment.po
core/priv/gettext/en/LC_MESSAGES/eyra-consent.po
core/priv/gettext/nl/LC_MESSAGES/eyra-assignment.po
core/priv/gettext/nl/LC_MESSAGES/eyra-consent.po
core/test/systems/consent/_public_test.exs

German translations first draft

Port mannheim german copy

---

core/priv/gettext/en/LC_MESSAGES/eyra-assignment.po
core/priv/gettext/en/LC_MESSAGES/eyra-content.po
core/priv/gettext/en/LC_MESSAGES/eyra-storage.po

Adjusted storage copy data donation and verified member copy when clicking publish.

Port mannheim storage copy

---

core/priv/gettext/en/LC_MESSAGES/eyra-next.po
core/priv/gettext/en/LC_MESSAGES/eyra-storage.po
core/priv/gettext/nl/LC_MESSAGES/eyra-next.po

Copy for data storage and some minor adjustments.

Copy data storage

---

core/priv/gettext/en/LC_MESSAGES/eyra-assignment.po
core/priv/gettext/en/LC_MESSAGES/eyra-ui.po

Adjusted the copy of the consent page skip warning

Master copy skip consent page warning

---

core/bundles/next/lib/account/session_controller.ex
core/bundles/self/lib/account/session_controller.ex
core/config/dev.exs
core/lib/core_web.ex
core/lib/core_web/controllers/apns_device_token_controller.ex
core/lib/core_web/controllers/error_controller.ex
core/lib/core_web/controllers/fake_alliance_controller.ex
core/lib/core_web/controllers/fallback_controller.ex
core/lib/core_web/controllers/health_controller.ex
core/lib/core_web/controllers/uploaded_file.ex
core/lib/core_web/timezone_controller.ex
core/lib/core_web/viewport_controller.ex
core/systems/account/settings_controller.ex
core/systems/alliance/controller.ex
core/systems/assignment/centerdata/fakeapi_controller.ex
core/systems/assignment/controller.ex
core/systems/assignment/external_panel_controller.ex
core/systems/graphite/export_controller.ex
core/systems/graphite/tool_controller.ex
core/systems/storage/controller.ex

Improve compile time Hero.ex

---

core/priv/gettext/en/LC_MESSAGES/eyra-manual.po

Updated manual instructions in the instruction manual block (workflow builder).

Updated manual instructions

---

core/priv/gettext/de/LC_MESSAGES/eyra-manual.po
core/priv/gettext/en/LC_MESSAGES/eyra-manual.po
core/priv/gettext/it/LC_MESSAGES/eyra-manual.po
core/priv/gettext/nl/LC_MESSAGES/eyra-manual.po

Updated the copy for the participant manual in English, Dutch, German and Italian.

Updated copy

---

core/priv/gettext/de/LC_MESSAGES/eyra-manual.po
core/priv/gettext/it/LC_MESSAGES/eyra-manual.po
core/priv/gettext/nl/LC_MESSAGES/eyra-manual.po

Updated the copy of the previous and next buttons.

Updated copy participant manual

---

SELFHOSTING.md

Added a storage customization section to selfhosting.md for instructions on how to change the built-in storage.

Added storage to selfhosting.md

---

core/priv/gettext/de/LC_MESSAGES/eyra-alliance.po
core/priv/gettext/de/LC_MESSAGES/eyra-feldspar.po
core/priv/gettext/de/LC_MESSAGES/eyra-manual.po
core/priv/gettext/de/LC_MESSAGES/eyra-pixel.po
core/priv/gettext/en/LC_MESSAGES/eyra-alliance.po
core/priv/gettext/en/LC_MESSAGES/eyra-feldspar.po
core/priv/gettext/en/LC_MESSAGES/eyra-pixel.po
core/priv/gettext/it/LC_MESSAGES/eyra-alliance.po
core/priv/gettext/it/LC_MESSAGES/eyra-feldspar.po
core/priv/gettext/it/LC_MESSAGES/eyra-manual.po
core/priv/gettext/it/LC_MESSAGES/eyra-pixel.po
core/priv/gettext/nl/LC_MESSAGES/eyra-alliance.po
core/priv/gettext/nl/LC_MESSAGES/eyra-feldspar.po
core/priv/gettext/nl/LC_MESSAGES/eyra-manual.po
core/priv/gettext/nl/LC_MESSAGES/eyra-pixel.po

Added copy for the manual, start screen questionnaire and start screen data donation.

Copy milestone 11

---

core/assets/js/feldspar_app.js

This ensures that initialization of Feldspar apps in a reliable way. It fixes an issue with unreliable loading with apps built on the new Feldspar framework release.

FeldsparApp now supports explicit app-loaded event

---

core/bundles/next/lib/account/signin_page.ex
core/frameworks/pixel/components/alert-banner.ex
core/systems/account/confirm_token.ex
core/test/core_web/live/user/confirm_token_test.exs

https://3.basecamp.com/5734045/buckets/35926565/todos/8455443371

feat: display persistent alert banner after account confirmation

---

core/assets/tailwind.config.js
core/priv/gettext/de/LC_MESSAGES/eyra-crew.po
core/priv/gettext/de/LC_MESSAGES/eyra-home.po
core/priv/gettext/en/LC_MESSAGES/eyra-crew.po
core/priv/gettext/en/LC_MESSAGES/eyra-home.po
core/priv/gettext/it/LC_MESSAGES/eyra-crew.po
core/priv/gettext/it/LC_MESSAGES/eyra-home.po
core/priv/gettext/nl/LC_MESSAGES/eyra-crew.po
core/priv/gettext/nl/LC_MESSAGES/eyra-home.po
core/systems/home/html.ex
core/test/core_web/controllers/user_session_controller_test.exs

Updated the copy of the Next landing page in 4 languages: EN, NL, DE, IT.

Updated copy landing page

---

core/priv/gettext/de/LC_MESSAGES/eyra-crew.po
core/priv/gettext/en/LC_MESSAGES/eyra-crew.po
core/priv/gettext/it/LC_MESSAGES/eyra-crew.po
core/priv/gettext/nl/LC_MESSAGES/eyra-crew.po

Update intro text for all 4 languages.

Updated intro Next landing page

---

core/systems/account/user_profile_form.ex
core/systems/promotion/form_view.ex
core/systems/zircon/screening/import_form.ex

https://3.basecamp.com/5734045/buckets/35926565/todos/8797651199
https://3.basecamp.com/5734045/buckets/35926565/todos/8797699289

fix: update process_file to use public_url instead of url
